/**
 * gen-keys.mjs — write src/lib/keys.generated.ts from .env.local.
 *
 * Runs before dev and before build. Deliberately not done through Vite's
 * import.meta.env or define(): both silently produced an empty value here,
 * and a credential that fails quietly is the worst possible failure mode.
 * A generated file can be opened and read, so if it is ever wrong it is
 * obvious rather than mysterious.
 *
 * The output is gitignored. Nothing secret is ever committed.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envFile = join(root, '.env.local');
const outFile = join(root, 'src', 'lib', 'keys.generated.ts');

/** Minimal KEY=value parser. Comments and blank lines are skipped. */
function parseEnv(text) {
  const out = {};
  for (const rawLine of text.replace(/^﻿/, '').split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const env = existsSync(envFile) ? parseEnv(readFileSync(envFile, 'utf8')) : {};

const chat = env.VITE_CHAT_OPENROUTER_KEY ?? '';
const code = env.VITE_CODE_OPENROUTER_KEY ?? '';
const tavily = env.VITE_CODE_TAVILY_KEY ?? '';

const body = `/**
 * GENERATED by scripts/gen-keys.mjs — do not edit, and do not commit.
 *
 * Chat and Code carry separate credentials. Neither mode reads the other's.
 */
export const CHAT_KEY_RAW = ${JSON.stringify(chat)};
export const CODE_KEY_RAW = ${JSON.stringify(code)};
export const TAVILY_KEY_RAW = ${JSON.stringify(tavily)};
`;

writeFileSync(outFile, body, 'utf8');

const mask = (v) => (v ? `${v.length} chars` : 'not set');
console.log(
  `[gen-keys] chat=${mask(chat)}  code=${mask(code)}  tavily=${mask(tavily)}`,
);

if (!chat || !code) {
  console.warn(
    '[gen-keys] warning: a credential is missing. Check .env.local — the app ' +
    'will build, but that mode will report itself as unconfigured.',
  );
}
